### ISSUE TITLE
xserver/xsession configurations

### ISSUE THREAD

**Issue by eyadsibai** [Th0rgal/horus-nix-home#2]
thank you for the repo!

I am interested in NixOS too. I would appreciate it if you could share ur NixOS configs too. (especially the xsession/xserver ...etc)

**Comment by Th0rgal** [comment]
You're welcome! Here is my system configuration: https://github.com/Th0rgal/horus-nix-system

**Comment by eyadsibai** [comment]
Hi ... I have been trying to use your config to use enable i3 with home-manager... but unfortunately i3 is not being started with your config. I even looked at your system config. Is there something else needed?

**Comment by Th0rgal** [comment]
> Hi ... I have been trying to use your config to use enable i3 with home-manager... but unfortunately i3 is not being started with your config. I even looked at your system config. Is there something else needed?

Hey, no it should be good, that's what I am using. Do you have some logs?

**Comment by eyadsibai** [comment]
I had to do this to make it work 

https://discourse.nixos.org/t/opening-i3-from-home-manager-automatically/4849/8
